site_web/src/MyfreelanceBundle/Entity/Project.php
<?php

namespace MyfreelanceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Project
 *
 * @ORM\Table(name="projet")
 * @ORM\Entity(repositoryClass="MyfreelanceBundle\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="date")
     */
    private $date;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text",nullable=true)
     */
    private $description;
    
    /**
     * @ORM\OneToMany(targetEntity="Ticket",mappedBy="project")
     */
    private $ticketList;
    
    /**
     *
     * @ORM\ManyToOne(targetEntity="Customer",inversedBy="projectList")
     */
    private $customer;


    public static function newProject(Customer $customer){
        $project = new Project();
        $project->setDate(new \DateTime('NOW'));
        $project->setCustomer($customer);
        
        return $project;
        
    }
    
    public function getNumberTicket(){
        return $this->getTicketList()->count();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Project
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Project
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Project
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set customer
     *
     * @param \MyfreelanceBundle\Entity\Customer $customer
     *
     * @return Project
     */
    public function setCustomer(\MyfreelanceBundle\Entity\Customer $customer = null)
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * Get customer
     *
     * @return \MyfreelanceBundle\Entity\Customer
     */
    public function getCustomer()
    {
        return $this->customer;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->ticketList = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add ticketList
     *
     * @param \MyfreelanceBundle\Entity\Ticket $ticketList
     *
     * @return Project
     */
    public function addTicketList(\MyfreelanceBundle\Entity\Ticket $ticketList)
    {
        $this->ticketList[] = $ticketList;

        return $this;
    }

    /**
     * Remove ticketList
     *
     * @param \MyfreelanceBundle\Entity\Ticket $ticketList
     */
    public function removeTicketList(\MyfreelanceBundle\Entity\Ticket $ticketList)
    {
        $this->ticketList->removeElement($ticketList);
    }

    /**
     * Get ticketList
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTicketList()
    {
        return $this->ticketList;
    }
    
    public function advancement(){
        return 0.5;
    }
    
    public function percentageAdvancement(){
        return $this->advancement()*100;
    }
    
    public function isDeletable(){
        return $this->getTicketList()->count()<=0;
    }
    
    public function countAllTicket(){
        return $this->getTicketList()->count();
    }
    
    public function countOpenTicket(){
        $i = 0;
        foreach($this->getTicketList() as $ticket){
            ($ticket->getState()->getName() == 'fini')?:$i++;
        }
        return $i;
    }
}

site_web/src/MyfreelanceBundle/Controller/ParameterController.php
<?php

namespace MyfreelanceBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use MyfreelanceBundle\Entity\Customer;
use MyfreelanceBundle\Form\CustomerType;
use MyfreelanceBundle\Form\ProjectType;
use Symfony\Component\HttpFoundation\Request;
use MyfreelanceBundle\Entity\Project;

class ParameterController extends Controller
{
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        
        $customerList = $em->getRepository("MyfreelanceBundle:Customer")->findByProvider($this->getUser()->getId()); 
        
        return $this->render('MyfreelanceBundle:parameter:index.html.twig',array('customerList'=>$customerList));
    }
    
    public function editCustomerAction(Request $request){
         $em = $this->getDoctrine()->getManager();
         
         if($request->query->has('idCustomer')){
             $customerId = $request->query->get('idCustomer');
             $customer = $em->getRepository("MyfreelanceBundle:Customer")->find($customerId);
         }else{
            $customer = new Customer($this->getUser());
            
         }
         $form = $this->createForm(CustomerType::class,$customer)
                 ->handleRequest($request);
         
         if($form->isValid()){
             $em->persist($customer);
             $em->flush();
             $this->addFlash('success',"Le client {$customer->getName()} a été faite");
             
             return $this->redirectToRoute("myfreelance_parameter_customer_index");
         }
         
         return $this->render('MyfreelanceBundle:parameter:edit_customer.html.twig',array('form'=>$form->createView()));
    }
    
    public function editProjectAction(Request $request){
        $em = $this->getDoctrine()->getManager();
        if($request->query->has('idCustomer')){
            $idCustomer = $request->query->get('idCustomer');
            $customer = $em->getRepository("MyfreelanceBundle:Customer")->find($idCustomer);
            $project = Project::newProject($customer);
        }elseif($request->query->has('idProject')){
            $projectId = $request->query->get('idProject');
            $project =$em->getRepository("MyfreelanceBundle:Project")->find($projectId);
            $customer = $project->getCustomer();
            
        }else{
         throw new \Symfony\Component\Config\Definition\Exception\Exception("no definitive project");  
        }
        
        $form = $this->createForm(ProjectType::class,$project)->handleRequest($request);
        
        if($form->isValid()){
             $em->persist($project);
             $em->flush();
             $this->addFlash('success',"Le Projet {$customer->getName()} a été faite");
             
             return $this->redirectToRoute("myfreelance_parameter_customer_index");
         }
        return $this->render("MyfreelanceBundle:parameter:edit_project.html.twig",array('form'=>$form->createView()));
    }
    
     public function deleteProjectAction(Project $project){
        if($project->getNumberTicket() > 0)
            throw new \Exception("Can't delete project");
        
        $em = $this->getDoctrine()->getManager();
        dump($this);die;
        $em->remove($project);
        
        $this->redirectToRoute("coucou");
        
    }
}

site_web/src/MyfreelanceBundle/Resources/views/parameter/edit_customer.html.twig
{% extends "MyfreelanceBundle::template.html.twig" %}


{% block title %}
    Edition client
{% endblock %}
{% block body %}
    <div class="container-fluid p-t-15">
        <div class="box">
            <div class="box-body collapse in">
                {{form_start(form)}}
                {%for elem in form %}
                    {{form_row(elem)}}
                {% endfor %}
                <input type="submit" value="valider" class="btn btn-primary">
                {{form_end(form)}}
            </div>
        </div>
    </div>
{% endblock %}

site_web/src/MyfreelanceBundle/Resources/views/parameter/edit_project.html.twig
{% extends "MyfreelanceBundle::template.html.twig" %}


{% block title %}
    Edition Projet -
    {% set projet = form.vars.value%}
    {{dump(projet.customer.name)}}
{% endblock %}
{% block body %}
    <div class="container-fluid p-t-15">
        <div class="box">
            <div class="box-body collapse in">
                {{form_start(form)}}
                {%for elem in form %}
                    {{form_row(elem)}}
                {% endfor %}
                <input type="submit" value="valider" class="btn btn-primary">
                {{form_end(form)}}
            </div>
        </div>
    </div>
{% endblock %}

site_web/src/MyfreelanceBundle/Resources/views/parameter/index.html.twig
{% extends "MyfreelanceBundle::template.html.twig" %}


{% block title %}
    Gestion des Clients
{% endblock %}
{% block body %}
<div class="container-fluid p-t-15">
    <div class="row">
        <a href="{{path('myfreelance_parameter_customer_add')}}" class="btn btn-rect btn-default mar-btn">Ajout</a>
    </div>
    {% for customer in customerList %}
        
 
    <div class="row">
        <div class="box shadow-3dp">
          <header>
            <h4>{{customer.id ~"."~customer.name}}</h4>
            <a class="btn" href="{{path('myfreelance_parameter_customer_edit',{'idCustomer':customer.id})}}">edit</a>
            <a class="btn" href="{{path('myfreelance_parameter_project_add',{'idCustomer':customer.id})}}">Add project</a>
            
            <!-- begin box-tools -->
            <div class="box-tools">
              <a class="fa fa-fw fa-minus" href="#" data-box="collapse"></a>
              <a class="fa fa-fw fa-square-o" href="#" data-fullscreen="box"></a>
              <a class="fa fa-fw fa-refresh" href="#" data-box="refresh"></a>
              <a class="fa fa-fw fa-times" href="#" data-box="close"></a>
            </div>
            <!-- END: box-tools -->
          </header>
          <div class="box-body collapse in">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nom</th>
                        <th>Date</th>
                        <th>Nb ticket</th>
                        <th>Avancement</th>
                        <th></th>
                    </tr>
                        
                </thead>
              <tbody>
                      {% for project in customer.projectList %}
                          <tr>
                              <td>{{project.id}}</td>
                              <td>{{project.name}}</td>
                              <td>{{project.date|date('d/m/Y')}}</td>
                              <td>{{project.numberTicket}}</td>
                              <td>
                                <div class="progress is-xs m-a-0 m-t-10">
                                  <div class="progress-bar" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: {{project.percentageAdvancement}}%;">
                                    <span class="sr-only">20% Complete</span>
                                  </div>
                                </div>
                              </td>
                              <td><a href="{{path('myfreelance_parameter_project_edit',{'idProject':project.id})}}">edit</a></td>
                              <td>{% if project.isDeletable %}<a href="{{path('myfreelance_parameter_project_delete',{'id':project.id})}}">delete</a>{% endif %}</td>
                              <td><a href="{{path('myfreelance_project_index',{'idProject':project.id})}}">voir</a></td>
                              
                          </tr>
                      {% endfor %}
                
                  
                
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
   {% endfor %}
{% endblock %}