site_web/src/MyfreelanceBundle/Entity/Bill.php
<?php

namespace MyfreelanceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Bill
 *
 * @ORM\Table(name="bill")
 * @ORM\Entity(repositoryClass="MyfreelanceBundle\Repository\BillRepository")
 */
class Bill
{
    const NOT_PAY = 1;
    const PAY = 2;
    const CONSTRUCT = 0;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     */
    private $date;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="settlementDate", type="datetime",nullable= true)
     */
    private $settlementDate;

    /**
     * @var int
     *
     * @ORM\Column(name="etat", type="integer")
     */
    private $etat;
    
    
    /**
     *  @ORM\ManyToOne(targetEntity="CustomerSociety",inversedBy="billList")
    */
    private $customer;
    
    /**
     * @ORM\ManyToOne(targetEntity="ProviderSociety",inversedBy="billList")
     */
    private $provider;
    
    /**
     *  @ORM\OneToMany(targetEntity="Ticket",mappedBy="bill",cascade={"persist"})
     */
    private $ticketList;
    
  
    
    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $title;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Bill
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set settlementDate
     *
     * @param \DateTime $settlementDate
     *
     * @return Bill
     */
    public function setSettlementDate($settlementDate)
    {
        $this->settlementDate = $settlementDate;

        return $this;
    }

    /**
     * Get settlementDate
     *
     * @return \DateTime
     */
    public function getSettlementDate()
    {
        return $this->settlementDate;
    }

    /**
     * Set etat
     *
     * @param integer $etat
     *
     * @return Bill
     */
    public function setEtat($etat)
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * Get etat
     *
     * @return int
     */
    public function getEtat()
    {
        return $this->etat;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->ticketList = new \Doctrine\Common\Collections\ArrayCollection();
    }



     
   

    public function getTitle() {
        return $this->title;
    }

    public function setTitle($title) {
        $this->title = $title;
    }

        /**
     * Add ticketList
     *
     * @param \MyfreelanceBundle\Entity\Ticket $ticketList
     *
     * @return Bill
     */
    public function addTicketList(\MyfreelanceBundle\Entity\Ticket $ticket)
    {
        $this->ticketList[] = $ticket;
        $ticket->setBill($this);

        return $this;
    }

    /**
     * Remove ticketList
     *
     * @param \MyfreelanceBundle\Entity\Ticket $ticketList
     */
    public function removeTicketList(\MyfreelanceBundle\Entity\Ticket $ticketList)
    {
        $this->ticketList->removeElement($ticketList);
    }

    /**
     * Get ticketList
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTicketList()
    {
        return $this->ticketList;
    }
    
    public function getNumero(){
        return str_pad($this->id,6,0,STR_PAD_LEFT);
    }
    
    public function becomeNotPay(){
        $this->etat = $this::NOT_PAY;
    }
    
    public function etatLabel(){
        switch($this->etat){
            case self::CONSTRUCT:
                return "Construction";
                break;
            case self::NOT_PAY:
                return 'Non Payer';
                break;
            case self::PAY:
                return "pay";
                break;
        }
    }
    
    
    public function isConstruct(){
        return $this->etat == self::CONSTRUCT;
    }
    
    public function getPriceHT(){
        $price = 0;
        foreach($this->getTicketList() as $ticket){
            $price += $ticket->getPrice();
        }
        return $price;
        
    }
    
    public function getPriceTTC(){
        return $this->getPriceHT();
    }



    /**
     * Set customer
     *
     * @param \MyfreelanceBundle\Entity\CustomerSociety $customer
     *
     * @return Bill
     */
    public function setCustomer(\MyfreelanceBundle\Entity\CustomerSociety $customer = null)
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * Get customer
     *
     * @return \MyfreelanceBundle\Entity\CustomerSociety
     */
    public function getCustomer()
    {
        return $this->customer;
    }

    /**
     * Set provider
     *
     * @param \MyfreelanceBundle\Entity\ProviderSociety $provider
     *
     * @return Bill
     */
    public function setProvider(\MyfreelanceBundle\Entity\ProviderSociety $provider = null)
    {
        $this->provider = $provider;

        return $this;
    }

    /**
     * Get provider
     *
     * @return \MyfreelanceBundle\Entity\ProviderSociety
     */
    public function getProvider()
    {
        return $this->provider;
    }
}

site_web/src/MyfreelanceBundle/Entity/Ticket.php
<?php

namespace MyfreelanceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Ticket
 *
 * @ORM\Table(name="ticket")
 * @ORM\Entity(repositoryClass="MyfreelanceBundle\Repository\TicketRepository")
 */
class Ticket
{
    
    const PRIX_HEURE = 30;
    const STATE_UNTREATED = 0;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="startDate", type="datetime")
     */
    private $startDate;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text",nullable=true)
     */
    private $description;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="Type", inversedBy="taskList")
     */
    private $type;
    
     /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="State", inversedBy="taskList")
     */
    private $state;
    
    /**
     * @ORM\ManyToOne(targetEntity="Bill",inversedBy="ticketList",cascade={"persist"})
     */
    private $bill;
    /**
     *
     * @var float
     * 
     * @ORM\Column(name="percentage",type="float",options={"comments":"pourcentage d'avancement"})
     * 
     * 
     */
    private $percentage = 0;

    
    /**
     * @ORM\ManyToOne(targetEntity="Project",inversedBy="ticketList")
     */
    private $project;
    
    /**
     * @ORM\OneToMany(targetEntity="Task",mappedBy="ticket")
     */
    private $taskList;
    
    /**
     * @ORM\Column(name="price",type="float",nullable=true)
     */
    private $price;
    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Ticket
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set startDate
     *
     * @param \DateTime $startDate
     *
     * @return Ticket
     */
    public function setStartDate($startDate)
    {
        $this->startDate = $startDate;

        return $this;
    }

    /**
     * Get startDate
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Ticket
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->taskList = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set state
     *
     * @param integer $state
     *
     * @return Ticket
     */
    public function setState($state)
    {
        $this->state = $state;

        return $this;
    }

    /**
     * Get state
     *
     * @return integer
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Set percentage
     *
     * @param float $percentage
     *
     * @return Ticket
     */
    public function setPercentage($percentage)
    {
        $this->percentage = $percentage;

        return $this;
    }

    /**
     * Get percentage
     *
     * @return float
     */
    public function getPercentage()
    {
        return (int) $this->percentage;
    }

    /**
     * Set project
     *
     * @param Project $project
     *
     * @return Ticket
     */
    public function setProject(Project $project = null)
    {
        $this->project = $project;

        return $this;
    }

    /**
     * Get project
     *
     * @return Project
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * Add taskList
     *
     * @param Task $taskList
     *
     * @return Ticket
     */
    public function addTaskList(Task $taskList)
    {
        $this->taskList[] = $taskList;

        return $this;
    }

    /**
     * Remove taskList
     *
     * @param Task $taskList
     */
    public function removeTaskList(Task $taskList)
    {
        $this->taskList->removeElement($taskList);
    }

    /**
     * Get taskList
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTaskList()
    {
        return $this->taskList;
    }
    
    public function stateLabel(){
        switch($this->state){
            case self::STATE_UNTREATED:
                return "non traiter";
        }
    }
    
    public static function createWithProject(Project $project){
       $ticket = new Ticket();
       $ticket->setProject($project);
       $ticket->setStartDate(new \DateTime('NOW'));
       
       return $ticket;
    }

    /**
     * Set type
     *
     * @param \MyfreelanceBundle\Entity\Type $type
     *
     * @return Ticket
     */
    public function setType(\MyfreelanceBundle\Entity\Type $type = null)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return \MyfreelanceBundle\Entity\Type
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set bill
     *
     * @param \MyfreelanceBundle\Entity\Bill $bill
     *
     * @return Ticket
     */
    public function setBill(\MyfreelanceBundle\Entity\Bill $bill = null)
    {
        $this->bill = $bill;

        return $this;
    }

    /**
     * Get bill
     *
     * @return \MyfreelanceBundle\Entity\Bill
     */
    public function getBill()
    {
        return $this->bill;
    }
    
    public function getPrice() {
        return $this->price;
    }

    public function setPrice($price) {
        $this->price = $price;
    }
    
    public function getNbHour(){
        
        $originDate = new \DateTime("1970-01-01 00:00:00.000000");
        foreach($this->getTaskList() as $task){
            $date = $task->getNbHour();
            $originDate->add($task->getNbHourInterval());
        }
        
        return $originDate;
    }
    
    /**
     * @return time to work in 
     */
        
    public function getTimeToWork(){
        $arg1 = $this->getNbHour();
        $nbMinute = 0;
        $nbMinute += ($arg1->format('h') > 0)?$arg1->format('h')*60:0;
        $nbMinute += ($arg1->format('d') > 1)?($arg1->format('d')-1)*60*24:0;
        $nbMinute += ($arg1->format('m') > 1)? ($arg1->format('m')-1)*60*24*31:0;
        $nbMinute += $arg1->format('i');
        return $nbMinute;
    }
    
    public function initPrice(){
        $price = ($this->getTimeToWork()/60)* 30;
        $this->setPrice($price);
        return $price;
    }
    


}

site_web/src/MyfreelanceBundle/Controller/BillController.php
<?php

namespace MyfreelanceBundle\Controller;

use MyfreelanceBundle\Entity\Bill;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Symfony\Component\HttpFoundation\Response;

/**
 * Bill controller.
 *
 */
class BillController extends Controller
{
    /**
     * Lists all bill entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $bills = $em->getRepository('MyfreelanceBundle:Bill')->findAll();

        return $this->render('MyfreelanceBundle:bill:index.html.twig', array(
            'bills' => $bills,
        ));
    }

    /**
     * Creates a new bill entity.
     *
     */
    public function newAction(Request $request)
    {
        $bill = new Bill();
        $form = $this->createForm('MyfreelanceBundle\Form\BillType', $bill);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $form = $this->createForm('MyfreelanceBundle\Form\BillType', $bill);
        
            $em = $this->getDoctrine()->getManager();
            foreach($bill->getTicketList() as $ticket){
                $bill->addTicketList($ticket);
            }
            
            $em->flush();
//            dump($bill);die;

            return $this->redirectToRoute('myfreelance_bill_edit', array('id' => $bill->getId()));
        }
        return_view:
        return $this->render('MyfreelanceBundle:bill:new.html.twig', array(
            'bill' => $bill,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a bill entity.
     *
     */
    public function showAction(Bill $bill)
    {
        //version sans pdf
       $html = $this->render('MyfreelanceBundle:bill:bill.pdf.twig',array('bill'=>$bill));
       
       $filename = sprintf('test-%s.pdf', date('Y-m-d'));
        
       //$pdf = $this->get('knp_snappy.pdf')->getOutputFromHtml($html);
        return $html;
    }

    /**
     * Displays a form to edit an existing bill entity.
     *
     */
    public function editAction(Request $request, Bill $bill)
    {
        $deleteForm = $this->createDeleteForm($bill);
        $editForm = $this->createForm('MyfreelanceBundle\Form\BillEditType', $bill);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $bill->becomeNotPay();
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('myfreelance_bill_edit', array('id' => $bill->getId()));
        }

        return $this->render('MyfreelanceBundle:bill:edit.html.twig', array(
            'bill' => $bill,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a bill entity.
     *
     */
    public function deleteAction(Request $request, Bill $bill)
    {
        $form = $this->createDeleteForm($bill);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($bill);
            $em->flush();
        }

        return $this->redirectToRoute('myfreelance_bill_index');
    }

    /**
     * Creates a form to delete a bill entity.
     *
     * @param Bill $bill The bill entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Bill $bill)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('myfreelance_bill_delete', array('id' => $bill->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

site_web/src/MyfreelanceBundle/Controller/Customer/BillController.php
<?php
namespace MyfreelanceBundle\Controller\Customer;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use MyfreelanceBundle\Entity\Project;
use MyfreelanceBundle\Entity\Ticket;
use MyfreelanceBundle\Entity\Task;
use MyfreelanceBundle\Form\Customer\TaskCustomerType;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

use Symfony\Component\HttpFoundation\Request;

class BillController extends Controller{
   
    public function indexAction(){
        $em = $this->getDoctrine()->getManager();
        
        $billList = $em->getRepository("MyfreelanceBundle:Bill")->findByCustomer($this->getUser());
        return $this->render('MyfreelanceBundle:customer/bill:index.html.twig',array('billList'=>$billList));
        
    }
   
}

site_web/src/MyfreelanceBundle/Resources/views/bill/bill.pdf.twig
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body>
        <style>
            logo {
                padding-bottom: 10px;
            }
            table {
                font-family: arial, sans-serif;
                border-collapse: collapse;
                width: 100%;
            }

            td, th {
                border: 1px solid black;
                text-align: left;
                padding: 8px;
                text-align: center;
            }

            tr:nth-child(even) {
                background-color: #dddddd;
            }

            ul > li {
                list-style-type: none;
            }
        </style>

    <page>   

        <h2 style="align:center">Facture n° {{bill.numero}}</h2>
        {# INFORMATION SOCIETE #}
        {% set society = bill.provider %}
        <div>
            <ul>
                <li style="margin-bottom: 1em">{{society.name}}</li>

                <li>{{society.address}}</li>
                <li>{{society.zipCode ~" "~ society.city}}</li>
                <li>{{society.phone}}</li>
                <li>N° SIRET : {{society.siret}}</li>
            </ul>

            {# NFORMATION CLIENT #}
            {% set customer = bill.customer %}
            <div style="width: 50%;float: right;display: block">      
                Facturé à
                <ul>
                    <li>{{customer.name}}</li>
                    <li>{{customer.address}}</li>
                    <li>{{customer.zipCode ~ " "~ customer.city}}</li>
                </ul>
            </div>
            {# INFORMATION FACTURE #}

            <ul style="clear: both">
                <li>Date : {{bill.date|date('d/m/Y')}}</li>
                <li>Référence : {{bill.title }}</li>
                <li>Numéro de facture : {{bill.numero}}</li>
            </ul>

            {#  INFORMATION PRODUIT #}
            <table>
                <thead>
                    <tr>
                        <th>Titre</th>
                        <th>Description</th>
                        <th>Nombres d'heures</th>
                        <th>Prix</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ticket in  bill.ticketList %}
                        <tr>
                            <td>{{ticket.title}}</td>
                            <td>{{ticket.description}}</td>
                            <td>{{ticket.nbHour|time('h')}}</td>
                            <td>{{ticket.price|price}}</td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
            <div style="width:50%;float:right;">
                <table style="margin-top: 1em;">
                    <tr>
                        <td>Total Hors Taxe</td>
                        <td>{{bill.priceHT|price}}</td>
                    </tr>
                    <tr>
                        <td colspan="2">TVA non applicable, art 293 B du CGI</td>
                        {#<td>Total TTC en euros</td>
                        <td>{{ bill.priceTTC|price }}</td>#}
                    </tr>
                </table>
                
            </div>
            <ul style="clear: both">
                <li>Date limite de règlement : Aucune</li>
                <li>Taux des pénalités de retard : 0%</li>
                <li>Taux d'escompte: 0%</li>
            </ul>


    </page>
</body>
</html>

site_web/src/MyfreelanceBundle/Resources/views/bill/edit.html.twig
{% extends 'MyfreelanceBundle::template.html.twig' %}

{% block title %}
    State edit
{% endblock %}
{% block body %}
    <div class="box">
        <div class="box-body">

            {{ form_start(edit_form) }}
                
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>titre<th>
                        <th>Nombre heures</th>
                    </tr>
                </thead>
                <tbody>
                {% for ticket in edit_form.ticketList %}
                    <tr>
                        <td>#{{ticket.vars.value.id}}</td>
                        <td>{{ticket.vars.value.title}}</td>
                        <td>{{ticket.vars.value.nbHour|time}}</td>
                        <td>{{form_widget(ticket)}}</td>
                {% endfor %}
                <tbody>
            </table>
                <input class="btn btn-default" type="submit" value="Valider" />
            {{ form_end(edit_form) }}

            
            <a class="btn btn-default" href="{{ path('myfreelance_type_index') }}">Back to the list</a>
            {{ form_start(delete_form) }}
                <input class="btn btn-danger" type="submit" value="Delete">
            {{ form_end(delete_form) }}
        </div>
    </div>
{% endblock %}

site_web/src/MyfreelanceBundle/Resources/views/bill/index.html.twig
{% extends 'MyfreelanceBundle::template.html.twig' %}

{% block body %}
    <div class="box">
        <div class="box-body">
                <a href="{{ path('myfreelance_bill_new') }}" class="btn btn-default">Creer une facture</a>

                <h1>States list</h1>

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>numero</th>
                            <th>Date</th>
                            <th>Etat</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for bill in bills %}
                        <tr>
                            <td><a href="{{ path('myfreelance_bill_show', { 'id': bill.id }) }}">{{ bill.numero }}</a></td>
                            <td>{{bill.date|date('d/m/Y')}}</td>
                            <td>{{bill.etatLabel}}</td>
                            <td>
                                {% if bill.isConstruct %}
                                <a class="btn btn-default" href="{{ path('myfreelance_bill_edit', { 'id': bill.id }) }}">edit</a>
                                {% else %}
                                    <a class="btn btn-default" target="_blanc" href="{{path('myfreelance_bill_show',{'id':bill.id})}}" >Voir</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>
{% endblock %}

site_web/src/MyfreelanceBundle/Resources/views/bill/new.html.twig
{% extends 'MyfreelanceBundle::template.html.twig' %}

{% block body %}
    <div class="box">
        <div class="box-body">
    <h1>State creation</h1>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <input class="btn btn-primary" type="submit" value="Create" />
          <a class="btn btn-default" href="{{ path('myfreelance_type_index') }}">Back to the list</a>
        
    {{ form_end(form) }}

      
        </div>
    </div>
{% endblock %}

site_web/src/MyfreelanceBundle/Resources/views/bill/test.pdf.twig
COUCOU